import { defineStore } from "pinia";
import { useFilterStore } from "./filterStore";

export const useGoodsStore = defineStore("goods", {
  state: () => ({
    goods: [
      {
        id: 1,
        brand: "balenciaga",
        name: "Balenciaga Runner",
        img: "sneakers",
        category: "Обувь",
        size: "42",
        season: "лето",
        old_price: 14990,
        new_price: 9990,
        discount: "33%",
      },
      {
        id: 2,
        brand: "prada",
        name: "Prada Re-Nylon Hoodie",
        img: "hoodie",
        category: "Верх",
        size: "M",
        season: "зима",
        old_price: null,
        new_price: 34990,
        discount: null,
      },
      {
        id: 3,
        brand: "yori sport",
        name: "Yorisport Mainlane Pants",
        img: "pants",
        category: "Низ",
        size: "L",
        season: "лето",
        old_price: 7990,
        new_price: 5990,
        discount: "25%",
      },
      {
        id: 4,
        brand: "givenchy",
        name: "Givenchy Logo T-Shirt",
        img: "tshirt",
        category: "Верх",
        size: "S",
        season: "лето",
        old_price: null,
        new_price: 12990,
        discount: null,
      },
      {
        id: 5,
        brand: "maison margiela",
        name: "Margiela Tabi Boots",
        img: "boots",
        category: "Обувь",
        size: "38",
        season: "осень",
        old_price: 89990,
        new_price: 62990,
        discount: "30%",
      },
      {
        id: 6,
        brand: "vetements",
        name: "Vetements Hoodie",
        img: "hoodie",
        category: "Верх",
        size: "XL",
        season: "зима",
        old_price: 75990,
        new_price: 44990,
        discount: "41%",
      },
      {
        id: 7,
        brand: "balenciaga",
        name: "Balenciaga Speed Trainer",
        img: "sneakers",
        category: "Обувь",
        size: "41",
        season: "весна",
        old_price: null,
        new_price: 59990,
        discount: null,
      },
      {
        id: 8,
        brand: "prada",
        name: "Prada Saffiano Belt",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "круглогодичный",
        old_price: 45990,
        new_price: 31990,
        discount: "30%",
      },
      {
        id: 9,
        brand: "yori sport",
        name: "Yorisport Joggers",
        img: "pants",
        category: "Низ",
        size: "M",
        season: "весна",
        old_price: 8990,
        new_price: 6290,
        discount: "30%",
      },
      {
        id: 10,
        brand: "givenchy",
        name: "Givenchy Shark Hoodie",
        img: "hoodie",
        category: "Верх",
        size: "L",
        season: "зима",
        old_price: null,
        new_price: 89990,
        discount: null,
      },
      {
        id: 11,
        brand: "maison margiela",
        name: "Margiela Replica Sneakers",
        img: "sneakers",
        category: "Обувь",
        size: "43",
        season: "лето",
        old_price: 65990,
        new_price: 42990,
        discount: "35%",
      },
      {
        id: 12,
        brand: "vetements",
        name: "Vetements Metal Logo Cap",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "лето",
        old_price: null,
        new_price: 21990,
        discount: null,
      },
      {
        id: 13,
        brand: "balenciaga",
        name: "Balenciaga Track Jacket",
        img: "jacket",
        category: "Верх",
        size: "M",
        season: "весна",
        old_price: 129990,
        new_price: 77990,
        discount: "40%",
      },
      {
        id: 14,
        brand: "prada",
        name: "Prada Nylon Backpack",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "круглогодичный",
        old_price: null,
        new_price: 89990,
        discount: null,
      },
      {
        id: 15,
        brand: "yori sport",
        name: "Yorisport Tech Fleece",
        img: "sweatshirt",
        category: "Верх",
        size: "XL",
        season: "зима",
        old_price: 12990,
        new_price: 8990,
        discount: "31%",
      },
      {
        id: 16,
        brand: "givenchy",
        name: "Givenchy Distressed Jeans",
        img: "pants",
        category: "Низ",
        size: "32",
        season: "осень",
        old_price: 45990,
        new_price: 31990,
        discount: "30%",
      },
      {
        id: 17,
        brand: "maison margiela",
        name: "Margiela Gloves",
        img: "accessories",
        category: "Аксессуары",
        size: "M",
        season: "зима",
        old_price: null,
        new_price: 24990,
        discount: null,
      },
      {
        id: 18,
        brand: "vetements",
        name: "Vetements Long Sleeve",
        img: "tshirt",
        category: "Верх",
        size: "S",
        season: "весна",
        old_price: 32990,
        new_price: 22990,
        discount: "30%",
      },
      {
        id: 19,
        brand: "balenciaga",
        name: "Balenciaga Logo Socks",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "круглогодичный",
        old_price: null,
        new_price: 8990,
        discount: null,
      },
      {
        id: 20,
        brand: "prada",
        name: "Prada Sunglasses",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "лето",
        old_price: 45990,
        new_price: 31990,
        discount: "30%",
      },
      {
        id: 21,
        brand: "off-white",
        name: "Off-White Industrial Belt",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "круглогодичный",
        old_price: 21990,
        new_price: 14990,
        discount: "32%",
      },
      {
        id: 22,
        brand: "gucci",
        name: "Gucci Ace Sneakers",
        img: "sneakers",
        category: "Обувь",
        size: "42",
        season: "лето",
        old_price: 89990,
        new_price: 69990,
        discount: "22%",
      },
      {
        id: 23,
        brand: "loewe",
        name: "Loewe Anagram Hoodie",
        img: "hoodie",
        category: "Верх",
        size: "L",
        season: "осень",
        old_price: 59990,
        new_price: 44990,
        discount: "25%",
      },
      {
        id: 24,
        brand: "burberry",
        name: "Burberry Check Scarf",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "зима",
        old_price: null,
        new_price: 39990,
        discount: null,
      },
      {
        id: 25,
        brand: "rick owens",
        name: "Rick Owens Geobasket",
        img: "sneakers",
        category: "Обувь",
        size: "43",
        season: "осень",
        old_price: 119990,
        new_price: 83990,
        discount: "30%",
      },
      {
        id: 26,
        brand: "stone island",
        name: "Stone Island Cargo Pants",
        img: "pants",
        category: "Низ",
        size: "M",
        season: "весна",
        old_price: 39990,
        new_price: 29990,
        discount: "25%",
      },
      {
        id: 27,
        brand: "fear of god",
        name: "Fear of God Essentials Tee",
        img: "tshirt",
        category: "Верх",
        size: "L",
        season: "лето",
        old_price: null,
        new_price: 11990,
        discount: null,
      },
      {
        id: 29,
        brand: "heron preston",
        name: "Heron Preston Sweatpants",
        img: "pants",
        category: "Низ",
        size: "XL",
        season: "зима",
        old_price: 32990,
        new_price: 22990,
        discount: "30%",
      },
      {
        id: 30,
        brand: "acne studios",
        name: "Acne Studios Beanie",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "зима",
        old_price: 14990,
        new_price: 9990,
        discount: "33%",
      },
      {
        id: 31,
        brand: "raf simons",
        name: "Raf Simons Denim Jacket",
        img: "jacket",
        category: "Верх",
        size: "L",
        season: "весна",
        old_price: 89990,
        new_price: 62990,
        discount: "30%",
      },
      {
        id: 32,
        brand: "celine",
        name: "Celine Suede Boots",
        img: "boots",
        category: "Обувь",
        size: "40",
        season: "осень",
        old_price: 109990,
        new_price: 76990,
        discount: "30%",
      },
      {
        id: 33,
        brand: "alexander mcqueen",
        name: "McQueen Skull Scarf",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "осень",
        old_price: 29990,
        new_price: 20990,
        discount: "30%",
      },
      {
        id: 34,
        brand: "off-white",
        name: "Off-White Caravaggio Tee",
        img: "tshirt",
        category: "Верх",
        size: "M",
        season: "лето",
        old_price: null,
        new_price: 27990,
        discount: null,
      },
      {
        id: 35,
        brand: "gucci",
        name: "Gucci GG Marmont Wallet",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "круглогодичный",
        old_price: 45990,
        new_price: 31990,
        discount: "30%",
      },
      {
        id: 36,
        brand: "loewe",
        name: "Loewe Puzzle Bag",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "лето",
        old_price: 159990,
        new_price: 111990,
        discount: "30%",
      },
      {
        id: 37,
        brand: "burberry",
        name: "Burberry Wool Coat",
        img: "jacket",
        category: "Верх",
        size: "M",
        season: "зима",
        old_price: null,
        new_price: 139990,
        discount: null,
      },
      {
        id: 38,
        brand: "rick owens",
        name: "Rick Owens Long Tee",
        img: "tshirt",
        category: "Верх",
        size: "L",
        season: "весна",
        old_price: 32990,
        new_price: 22990,
        discount: "30%",
      },
      {
        id: 39,
        brand: "stone island",
        name: "Stone Island Sweater",
        img: "sweatshirt",
        category: "Верх",
        size: "L",
        season: "осень",
        old_price: 41990,
        new_price: 29990,
        discount: "29%",
      },
      {
        id: 40,
        brand: "fear of god",
        name: "Essentials Sweatshorts",
        img: "pants",
        category: "Низ",
        size: "M",
        season: "лето",
        old_price: 18990,
        new_price: 12990,
        discount: "32%",
      },
      {
        id: 42,
        brand: "heron preston",
        name: "Heron Preston Logo Cap",
        img: "accessories",
        category: "Аксессуары",
        size: "универсальный",
        season: "лето",
        old_price: null,
        new_price: 14990,
        discount: null,
      },
      {
        id: 43,
        brand: "acne studios",
        name: "Acne Studios Logo Hoodie",
        img: "hoodie",
        category: "Верх",
        size: "M",
        season: "зима",
        old_price: 39990,
        new_price: 27990,
        discount: "30%",
      },
      {
        id: 45,
        brand: "celine",
        name: "Celine Leather Jacket",
        img: "jacket",
        category: "Верх",
        size: "M",
        season: "осень",
        old_price: 179990,
        new_price: 125990,
        discount: "30%",
      },
      {
        id: 46,
        brand: "alexander mcqueen",
        name: "McQueen Sneakers",
        img: "sneakers",
        category: "Обувь",
        size: "41",
        season: "весна",
        old_price: 79990,
        new_price: 55990,
        discount: "30%",
      },
      {
        id: 47,
        brand: "off-white",
        name: "Off-White Diag Hoodie",
        img: "hoodie",
        category: "Верх",
        size: "XL",
        season: "зима",
        old_price: 74990,
        new_price: 52990,
        discount: "29%",
      },
      {
        id: 48,
        brand: "gucci",
        name: "Gucci Track Pants",
        img: "pants",
        category: "Низ",
        size: "L",
        season: "осень",
        old_price: null,
        new_price: 49990,
        discount: null,
      },
      {
        id: 49,
        brand: "loewe",
        name: "Loewe Technical Jacket",
        img: "jacket",
        category: "Верх",
        size: "XL",
        season: "зима",
        old_price: 139990,
        new_price: 97990,
        discount: "30%",
      },
      {
        id: 50,
        brand: "burberry",
        name: "Burberry Cotton Polo",
        img: "tshirt",
        category: "Верх",
        size: "M",
        season: "лето",
        old_price: 39990,
        new_price: 27990,
        discount: "30%",
      },
    ],
  }),

  getters: {
    filteredGoods(state) {
      const filterStore = useFilterStore();

      return state.goods.filter((product) => {
        const categoryMatch =
          filterStore.selectedCategories === 0 ||
          filterStore.selectedCategories.includes(product.category);

        const brandMatch =
          filterStore.selectedBrands === 0 ||
          filterStore.selectedBrands.includes(product.brand);

        const sizeMatch =
          filterStore.selectedSizes === 0 ||
          filterStore.selectedSizes.includes(product.size);

        const seasonMatch =
          filterStore.selectedSeasons === 0 ||
          filterStore.selectedSeasons.includes(product.season);

        const priceMatch =
          product.price >= filterStore.priceRange[0] &&
          product.price <= filterStore.priceRange[1];

        return (
          categoryMatch && brandMatch && sizeMatch && seasonMatch && priceMatch
        );
      });
    },
  },
});
